src/blog/urls.py
from django.urls import path

from blog.views import (
    article_list_view,
    article_detail_view,
    article_create_view,
    article_update_view,
    article_delete_view,
)

from blog.views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
)

from blog.views import (
    ArticleDetailView_1,
    ArticleListView_1,
    ArticleCreateView_1,
    ArticleUpdateView_1,
    ArticleDeleteView_1,
)

app_name = 'articles'
urlpatterns = [
    path('', ArticleListView_1.as_view(), name='article_list'),
    path('create/', ArticleCreateView_1.as_view(), name='article_create'),
    path('<int:id>/', ArticleDetailView_1.as_view(), name='article_detail'),
    path('<int:id>/update/', ArticleUpdateView_1.as_view(), name='article_update'),
    path('<int:id>/delete/', ArticleDeleteView_1.as_view(), name='article_delete'),
]

src/products/urls.py
from django.urls import path

from products.views import (
    product_list_view,
    product_detail_view,
    product_create_view,
    product_update_view,
    product_delete_view,
)

app_name = 'products'
urlpatterns = [
    path('', product_list_view, name='product_list'),
    path('create/', product_create_view, name='product_create'),
    path('<int:id>/', product_detail_view, name='product_detail'),
    path('<int:id>/update/', product_update_view, name='product_update'),
    path('<int:id>/delete/', product_delete_view, name='product_delete'),
]

src/trydjango/urls.py
from django.contrib import admin
from django.urls import include, path

from pages.views import home_view, contact_view, about_view

urlpatterns = [
    path('', home_view, name='home'),
    path('contact/', contact_view, name='contact'),
    path('about/', about_view, name='about'),
    path('admin/', admin.site.urls),

    path('products/', include('products.urls')),
    path('blog/', include('blog.urls'))
]

src/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>hello world</h1>
<p>This is an about template</p>
<p>
{{ my_text }}
{{ my_number }}
</p>

<ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
</ul>

{% for i in my_list %}
    {% if i == 10 %}
    <li>{{ forloop.counter }} - {{ i|add:10000 }}</li>
    {% else %}
    <li>{{ forloop.counter }} - {{ i }}</li>
    {% endif %}
{% endfor %}

{% endblock content %}

src/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Practice Project - Trydjango</title>
</head>
<body>
    {% include 'navbar.html' %}
    
    {% block content %}
        replace me
    {% endblock content %}
</body>

</html>

src/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<h1>hello world</h1>
<p>This is a contact template</p>
{% endblock content %}

src/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>hello world</h1>
{{ request.user }}
<p>This is a home template</p>
{% endblock content %}

src/templates/navbar.html
<nav>
    <ul>
        <li><a href="{% url 'products:product_list' %}">Product</a></li>
        <li><a href="{% url 'articles:article_list' %}">Article</a></li>
        <li><a href="{% url 'contact' %}">Contact</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
    </ul>
</nav>